### PR TITLE
Add PlantUML server support

### PR DESCRIPTION
**Pull request by logwolvy**
Add support for [PlantUML server](https://github.com/plantuml/plantuml-server)

**Motivation**
- Related feature request, https://github.com/shd101wyy/vscode-markdown-preview-enhanced/issues/255
- Security issues with plantuml binary (jar), https://github.com/qjebbs/vscode-plantuml#notice-1

### CODE REVIEW

**Comment by logwolvy** [comment]
@shd101wyy could you or someone you assign, review this PR?

**Comment by shd101wyy** [comment]
@logwolvy Sorry for the delay. Could you please provide me with an example plantuml server so I could try it out myself. Thanks!

**Comment by shd101wyy** [comment]
@logwolvy You probably also want to update the REAMDE.md file to add explanation of the `plantumlServer` config here https://github.com/shd101wyy/mume#markdown-engine-configuration. Thanks!

**Comment by logwolvy** [comment]
> @logwolvy Sorry for the delay. Could you please provide me with an example plantuml server so I could try it out myself. Thanks!

**Steps to test**
1. `docker run -d -p 8080:8080 plantuml/plantuml-server:tomcat` to run plantuml server
2. Use `plantumlServer` option as below,
```js
const engine = new mume.MarkdownEngine({
    filePath: "/path/to/puml/embedded/md",
    config: {
      configPath: configPath,
      previewTheme: "github-light.css",
      codeBlockTheme: "default.css",
      printBackground: true,
      enableScriptExecution: true,
      plantumlServer: "http://localhost:8080/svg/"   // <--- plantuml server endpoint
    },
});
```

👍

**Review by shd101wyy — APPROVED** [review]
LGTM. Thanks!

**Comment by shd101wyy** [comment]
@logwolvy Your feature is now supported in the latest version of mpe. Cheers! :+1:

**Pull request merged**
