### PR TITLE
Elm syntax highlighting with PrismJS

### PR DESCRIPTION
**Pull request by kachkaev**
Prism now supports syntax highlighting for elm, thanks to https://github.com/PrismJS/prism/pull/1174. This makes it possible to highlight elm code in the markdown output, which is what I implemented in this PR.

Because mume partially relies on `dependencies/*.js` instead of `node_modules`, here are the details of how I updated `dependencies/prism.js`:
1. Went to http://prismjs.com/download.html
1. Selected all languages
1. Downloaded the js file and saved it as `dependencies/prism.js`
1. In a rather large diff, searched for a line starting with `Prism.languages.elm=` and staged it

This means that PrismJS has not been updated as a whole. Although this ensures that mume does not break with this PR, it'd be great to generally keep in sync with prism as it gets updated. @shd101wyy could you please briefly describe how to generate `dependencies/prism.js` from source inside `dependencies/README.md`?

To be honest, I'd prefer to just sticking with `node_modules`, but I imagine there's been a really good reason to switch to a custom dependency management. Just curious: in which scenarios large `node_modules` ended up being a pain for `mume`? Can't remember that in other Node.js (i.e. not-in-browser) projects.

### CODE REVIEW

**Comment by shd101wyy** [comment]
Hi @kachkaev , I didn't choose node_modules for some packages because I had trouble packaging vscode extension. If I recall correctly, vscode extension has a size limit of `20mb`. There are also some reasons but I don't remember exactly.

I will have a look at your pull request when I have time.

Thank you very much for your contribution.

**Comment by shd101wyy** [comment]
Looks good to me. You can merge it at anytime. Thanks.

**Comment by kachkaev** [comment]
Thanks @shd101wyy! Would you like me to prepare a new release? I can't publish on npm, but could change the version, update changelog etc. Happy if you do that too, just asking because I know you're a bit busy now

**Comment by shd101wyy** [comment]
Thanks @kachkaev ! I will finish reviewing your pull requset [#34](https://github.com/shd101wyy/mume/pull/34) and [#31](https://github.com/shd101wyy/mume/pull/31) by the end of this week. Then we can publish a new version.

**Pull request merged**
