### PR TITLE
Split markdown engine: render enhancers

### PR DESCRIPTION
**Pull request by kachkaev**
Hi @shd101wyy!

Following your refactoring approval in https://github.com/shd101wyy/mume/issues/33, I'm glad to share my work on further splitting `markdown-engine.ts` into small narrow-focused modules. The main change in this PR is that certain parts of the rendering process have been extracted from `markdown-engine.ts` into what I called _render enhancers_. This is somewhat similar to what I did for custom markdown features in https://github.com/shd101wyy/mume/pull/34.

A render enhancer is just an asynchronous function stored in `src/render-enhancers`. It accepts `$` (cheerio document) with a few extra custom settings and mutates this cheerio document according to its role. Render enhancers are easy to understand, debug and combine together, because they are isolated from each other and self-sufficient.

The concept of render enhancers allowed me to split fenced math blocks, diagrams, code chunks and code formatting into separate TypeScript files, each being focused on one feasible & and easy-to-define task. It is now supereasy to toggle each of these features by simply commenting out a call to a particular enhancer inside the main render function – that's much less labour than it used to be!  What is also great is that with render enhancers, future contributors will be able to propose new `markdown-preview-enhanced` features with no need to add mini-patches across thousands of lines of code – just writing a new enhancer is likely to be enough! In fact, I might submit one new quite an exiting feature in the near future, so stay tuned 😉 

As a by-product of my work, here are a few minor functionality improvements:
* Fenced math blocks and diagrams now support `hide=false` attribute, which makes it possible to show both the output and the source, like in code chunks. This can be very useful in teaching materials, e.g. when explaining how mermaid or vega works.
* There is a new option `output_first=true` (or just `output_first` thanks to https://github.com/shd101wyy/mume/pull/31) in all fenced blocks. This makes it possible to swap the code listing and the output when both need to be shown.
* Diagrams and math now support `cmd=false` for cases when someone wants disable magick
* Code block info and import attributes are now normalized, so users are less likely to be misunderstood when they slightly deviate from the exact syntax. Block language is lowercased and all attribute names are `snake_cased` automatically. Check out test cases for `normalizeAttributes` and `normalizeBlockInfo` in `test/lib` for details.
* Importing `.dot`, `.gv`, `.vis`, `.mermaid`, `.plantuml` and `.puml` with `@import` now supports attributes, similar to how this used to be done for images before. These attributes work the same way as fenced code block attributes as you can easily guess.

I'll be happy with documenting the new features once this PR is agreed on and merged!

There are still things to improve in the logic of render enhancers. For example, we might find reasonable to re-define a boundary between a diagram and a code chunk (e.g. latex could go to diagrams so that it has `hide=true` by default etc). I left these possible changes for the future discussions, because my main goal in this PR was to refactor the structure of the rendering process as a whole without breaking things. What is also a bit far from ideal at the moment is dependency passing. Render enhancers are stateless, meaning that they do not depend on any changeable `this`, which makes them highly robust. Consequently, it is necessary to pass parts of the state from `markdown-engine` as additional arguments – this is so that settings like `MathRenderingOption` could be taken into account. What is great is that when we now look at our render function, we can know for sure what each enhancer depends on. However, the way this is currently being done is a bit rough because of how different parts of code used to be intertwined originally. In any case, untangling enhancer arguments is a minor task, which can be done at any time in future.

I hope I haven't introduced any regressions, but to ensure that, I'd really like my changes to be diligently reviewed. A few new markdowns in `test/integration/fixtures` may help with testing. It'd be great if we had more examples there, especially with edge cases!

Really looking forward to hearing what you think @shd101wyy and thanks again for making mume such a powerful markdown tool! 🎉  Your choice of TypeScript makes its future very exiting too!

### CODE REVIEW

**Comment by kachkaev** [comment]
@sheljohn if you're keen to look through the changes I've made, feel free to! I'll be happy to improve this PR if you discover any glitches.

**Comment by shd101wyy** [comment]
@kachkaev Nice job! Thank you ;)
I will review this pull request either this weekend or next weekend.

**Comment by kachkaev** [comment]
@shd101wyy feel free to ping me if you have any questions regarding the changes. I should be around till about 10pm UTC today.

**Comment by kachkaev** [comment]
Two more commits:
* upgraded `vega` and `vega-lite` libs by merging the latest `master` (https://github.com/shd101wyy/mume/pull/40/commits/c47e9808e7801a8aadf46ffa5742081ff9bc9172)
* wrapped raw code that gets added to the document for client-side rendering into an invisible div so that text does not flickr on page load (https://github.com/shd101wyy/mume/pull/40/commits/840b74aaf2248163afae872e208f2b62018cbc41)

**Comment by kachkaev** [comment]
There's one thing I don't quite understand in mume's work and it'd be great if you could have a look at it @shd101wyy. When I produce an html by [calling mume from Node.js](https://github.com/shd101wyy/markdown-preview-enhanced/issues/788#issuecomment-367133311) and add `console.log` into any of the _render enhancers_, the output is shown twice. This means that `markdown engine`'s `parseMD` is called twice and I'm wondering if this can be avoided. It feels like the current behaviour is somehow related to code chunk execution, but maybe it's possible to avoid double-render somehow?

**Comment by shd101wyy** [comment]
Hi @kachkaev 

Sorry I have been busy working on my tax report and applying for OPT extension, so I am not able to review your code this weekend. I promise to do that next week.

As for the `console.log` issue you mentioned previously, I don't know why it happened either.  
I will take a look at the code when I have time.  

Thank you

**Comment by shd101wyy** [comment]
@kachkaev Awesome pull request! Thank you very much!  
I learnt a lot about jest testing from your code. It's very meaningful. Thank you!  

Because a lot of people are complaining about MathJax not working in MPE package [MPE #775](https://github.com/shd101wyy/markdown-preview-enhanced/issues/775), I would like to release a quick fix for that tonight. 
So I would merge this pull request, then fix the MathJax issue, and release `mume@0.3.0`. 

As for the pull request #42 , I would like to add that feature in next release. 

Thank you very much ;)

**Comment by kachkaev** [comment]
Awesome! Really happy to see this PR merged – thanks for your time @shd101wyy! Feel free to look at #42 – it is quite small now after a rebase.

It'd be great if you could prettify all the code as I'm suggesting in the first point of https://github.com/shd101wyy/mume/issues/33#issuecomment-368038114 in one of your next contributions. It's a problematic to use Prettier on save before this happens, because a minor edit in a non-refactored file like `markdown-engine.ts` creates a diff with thousands of lines and it's very easy to do this by a mistake. So I currently have to use `"editor.formatOnSave": false` in VSCode config and format mume files manually. Obviously, I occasionally forget to do this and so the code I produce becomes uglier than it could 😃

**Pull request merged**
