### PR TITLE
Replace emoji with svg in ebook pdf

### LINKED ISSUE #85: Emojis not working in ebook pdf
When you export an ebook pdf none of the emojis show up

### PR DESCRIPTION
**Pull request by dlip**
Fixes #85 Replaces the emojis in the ebook pdf with twemoji svgs, I'm not sure this is the best replacement since visually they are a flatter style than what you see in the html render

### CODE REVIEW

**Comment by kachkaev** [comment]
Hi @shd101wyy I won’t be able to review in the next few days, could you please help?

**Comment by shd101wyy** [comment]
@kachkaev Sure I will take over. Thanks!

**Comment by shd101wyy** [comment]
Hi @dlip it looks good to me. Have you tested with your pdf? Thanks.

**Comment by dlip** [comment]
Here is my comparisons, it works but as you can see the twemoji has a slightly different look than puppeteer. I'm not sure if the emojis chrome uses are publicly available, I did find this [gitbook plugin](https://github.com/codeclou/gitbook-plugin-advanced-emoji/tree/master/assets/emojis) which uses emojis that are in png format so we could use that approach if we think being closer to chrome is more important than vector emojis.

### Puppeteer (uses bitmap for emoticons)

emojitest-puppeteer

### EBook no fix

emojitest-ebook-nofix

### EBook using twemoji SVG

emojitest-ebook-twemoji

**Comment by dlip** [comment]
On further inspection of the gitbook plugin, it only has icons for the [github emojis](https://api.github.com/emojis). I guess twemoji has the complete set of utf8 emojis?

**Comment by dlip** [comment]
I have a proposal:

To keep consistency between renderers, we can **always** use twemoji/some other svg emoji library for standard utf8 emojis even html rendering. SVG is the highest quality and is the smallest footprint to our package since we have to distribute these files.

For the unique github emojis we can use their pngs since there is no svg available.

**Comment by dlip** [comment]
Example of always using twemoji #88

**Comment by dlip** [comment]
I'm ok to merge this fix for pdf only for now, we can think about the more radical changes separately.

**Pull request merged**
