### PR TITLE
Setup TravisCI

### PR DESCRIPTION
**Pull request by shd101wyy**

### CODE REVIEW

**Comment by kachkaev** [comment]
Good stuff! The error says 

```
Forgot to run prettier? There are files without correct code style:
test/integration/fixtures/basics.md
test/integration/fixtures/code-chunks.md
```

I guess you just need to run `npm run format` to prettify two fixtures. Not sure why all worked on your machine though. Which OS are you using?

WDYT of adding a Travis badge to README.md? It will say `build: passing`. Check out an example here: https://github.com/gicentre/prettier-plugin-elm

**Comment by shd101wyy** [comment]
I did run prettier. I am using Ubuntu 16.04. maybe the issue is because of
the version of the nodes I installed or the OS. I will figure it out later.
Thank you!

**Comment by shd101wyy** [comment]
Hi @kachkaev , 

It works now. 
I can capture the prettier errors on my mac but not on my ubuntu 16.04 machine. It's quite weird.  
Anyways, the TravisCI works now. 

Thank you!

**Comment by kachkaev** [comment]
Speaking of prettier and ubuntu. Assuming that your dependencies are installed correctly, the only thing to blame I have in my head is path definitions. We are using a pretty convoluted glob "regexp" when running prettier and there is some chance that it's interpreted differently on Linux and MacOS. Can you try replacing our glob with something trivial, break formatting for some file and try `npm run format`? If the issue is in the file paths, indeed, that should work.

**Pull request merged**
