### PR TITLE
Refactor files for issue #33 task 1

### PR DESCRIPTION
**Pull request by shd101wyy**

### CODE REVIEW

**Comment by kachkaev** [comment]
Thanks for putting this together @shd101wyy – this PR is a breakthrough in the long run! I'm wondering what's the best balance between switching off the rules in `tslint.json` and getting a bug-free code, so would like to discuss our strategy here. In particular, I'm a bit concerned about these three rules:

* `"no-shadowed-variable"` – a shadowed variable is often a sign of a typo and it'd be great if we did not have such variables in the code. We can simply rename things like `i` → `i2` and as a reward get a useful warning bell in future.

* `"no-conditional-assignment"` – I used to fight bugs for hours simply because of having `a = b` instead of `a === b` in `if(...)`. It'd be great if we could avoid `=` when checking conditions and move the assignments before or after the ifs.

* `"no-unused-expression"` – unused expressions are also a sign of a bug, I had these. Therefore it'd be great to follow this rule and `// tslint:disable-next-line:no-unused-expression` in a couple of cases if that's strictly necessary.

Here are a few thoughts on the other rules you disabled:

* `"radix"` – I don't mind having this rule switched of, but replacing `parseInt(x)` with `parseInt(x, 10)` looks like a quick mechanical thing. Not sure this will ever save us from hard-to-catch bugs, but I used to have huge problems with `parseInt` when radix was not set explicitly. For instance, if you do `_.map(arr, radix)`, you're screwed up 😆  (I used to!)

* `"one-variable-per-declaration"` – again, not a critical thing, but IMO having `const` or `let` in front of _every_ variable declaration makes it much easier to scan through what you've got and also change one mode to another for a particular variable without creating a redundant git diff

* `"no-var-requires"` – I understand that we can't use `import` in 100% of cases, but I'd prefer having `// tslint:disable-next-line:no-var-requires` before every `require()`. This will make future contributors think twice before using `require` instead of `import`, which is a good thing.

How difficult would it be to enable the rules I mentioned? I completely understand that this not a very exiting task to do, but I hope we both see the benefits of having a continuously checked code that follows the highest standard! :100

**Comment by kachkaev** [comment]
Thanks for putting this together @shd101wyy – this PR is a breakthrough in the long run! I'm wondering what's the best balance between switching off the rules in `tslint.json` and getting a bug-free code, so would like to discuss our strategy here. In particular, I'm a bit concerned about these three rules:

* `"no-shadowed-variable"` – a shadowed variable is often a sign of a typo and it'd be great if we did not have such variables in the code. We can simply rename things like `i` → `i2` and as a reward get a useful warning bell in future.

* `"no-conditional-assignment"` – I used to fight bugs for hours simply because of having `a = b` instead of `a === b` in `if(...)`. It'd be great if we could avoid `=` when checking conditions and move the assignments before or after the ifs.

* `"no-unused-expression"` – unused expressions are also a sign of a bug, I had these. Therefore it'd be great to follow this rule and `// tslint:disable-next-line:no-unused-expression` in a couple of cases if that's strictly necessary.

Here are a few thoughts on the other rules you disabled:

* `"radix"` – I don't mind having this rule switched of, but replacing `parseInt(x)` with `parseInt(x, 10)` looks like a quick mechanical thing. Not sure this will ever save us from hard-to-catch bugs, but I used to have huge problems with `parseInt` when radix was not set explicitly. For instance, if you do `_.map(arr, radix)`, you're screwed up 😆  (I used to!)

* `"one-variable-per-declaration"` – again, not a critical thing, but IMO having `const` or `let` in front of _every_ variable declaration makes it much easier to scan through what you've got and also change one mode to another for a particular variable without creating a redundant git diff

* `"no-var-requires"` – I understand that we can't use `import` in 100% of cases, but I'd prefer having `// tslint:disable-next-line:no-var-requires` before every `require()`. This will make future contributors think twice before using `require` instead of `import`, which is a good thing.

How difficult would it be to enable the rules I mentioned? I completely understand that this not a very exiting task to do, but I hope we both see the benefits of having a continuously checked code that follows the highest standard! 💯

**Comment by shd101wyy** [comment]
@kachkaev Thank you for your comments. Yeah we could disable the rules the I added. I will do it this weekend or you can take over if you want. Thank you!

**Comment by kachkaev** [comment]
I was initially willing to do the refactoring myself so that the rules match, but then I realised that I can break something important because I don't have enough background knowledge. So it'd be great if you could author these changes, but I'm happy to answer any possible questions from you this weekend!

**Comment by shd101wyy** [comment]
@kachkaev all rules that you mentioned previously are removed now. I hope I don't break anything. 
I think we could start fixing bugs that were posted in mpe and vscode-mpe repository once this pull request is merged. Thank you very much.

**Pull request merged**
