### PR TITLE
Refactor parseAttributes() and implement shortcuts in attributes

### LINKED ISSUE #29: Allow for shortcuts in code chunk options
I'd like to propose an improvement to command chunk options and am curious what you think. Let's take this example:

````markdown
```python {cmd=true hide=true}
````

It seems intuitive to omit `=true` and simply write:
````markdown
```python {cmd hide}
````
However, the current implementation treats the above options as: `{cmd: hide}` because a space is the same as `=` for the [interpreter](https://github.com/shd101wyy/mume/blob/b73cc2f8d9f4bb0b0bb4515411bd8e8eabae3772/src/utility.ts#L456). This is less obvious, especially in cases like these ones:

````markdown
```python {cmd .class1 .class2 hide}
````
↓
`{ class: 'class1 class2', cmd: 'hide' }`

````markdown
```python {cmd}
````
↓
`{}`

````markdown
```python {cmd output="path.html" hide}
````
↓
`{ cmd: 'output', 'path.html': 'hide' }`

How about making `=` necessary for `key=value` options and when it is omitted, how about treating the input as `key=true`?

This improvement opens up a new range of opportunities for shortcuts, which can be very concise  and thus time-saving for advanced users. For example, `{h}` can unwrap to `{cmd=true hide=true}` in the background. I'm not proposing this next step at the moment, just sharing thoughts on future benefits I see.

I can submit a PR for assuming` =true` by default. WDYT?

### PR DESCRIPTION
**Pull request by kachkaev**
Closes #29 

The goal of this PR is to allow for shorcuts in code chunk attributes such as `{cmd hide}` for `{cmd=true hide=true}`.

While I'm reimplementing `parseAttributes()` to support the new functionality, I'll be happy to hear some feedback on the refactoring I've done in preparation for the changes. Function `parseAttributes()` has been moved to a separate module (`code-chunk-attributes.js`) and [`jest`](https://facebook.github.io/jest/) has been introduced to cover the code with unit tests. You can now `npm run test`.

WDYT @shd101wyy? Which test cases would you also include into `__tests__/code-chunk-attributes.js`? Just want to make sure I don't break anything while how `parseAttributes()` works.

### CODE REVIEW

**Comment by kachkaev** [comment]
The PR should be good to go. Happy to add more test cases before the PR is merged.

**Comment by shd101wyy** [comment]
Hello @kachkaev ,

This is awesome! I will have a look at your code this weekend.
And thanks for adding test cases.
I am not sure which docs to update, maybe [code-chunk.md](https://github.com/shd101wyy/markdown-preview-enhanced/blob/master/docs/code-chunk.md)?

Thank you very much ;)

**Comment by kachkaev** [comment]
Awesome! See https://github.com/shd101wyy/markdown-preview-enhanced/pull/753 for doc update suggestion.

If you want to run tests locally, make sure you `npm install` after `git pull ...`. Running `npm test` should work after that.

**Comment by shd101wyy** [comment]
Hi @kachkaev ,

I got the following error while running `npm install`.

```sh
➜  mume git:(kachkaev-refactor-parse-attributes) ✗ npm install

> @shd101wyy/mume@0.2.8 prepare /home/shd101wyy/GitHub/mume
> npm run build


> @shd101wyy/mume@0.2.8 build /home/shd101wyy/GitHub/mume
> tsc -p .

node_modules/@types/jest/index.d.ts(17,13): error TS2300: Duplicate identifier 'beforeEach'.
node_modules/@types/jest/index.d.ts(19,13): error TS2300: Duplicate identifier 'afterEach'.
node_modules/@types/mocha/index.d.ts(36,13): error TS2403: Subsequent variable declarations must have the same type.  Variable 'describe' must be of type 'Describe', but here has type 'IContextDefinition'.
node_modules/@types/mocha/index.d.ts(37,13): error TS2403: Subsequent variable declarations must have the same type.  Variable 'xdescribe' must be of type 'Describe', but here has type 'IContextDefinition'.
node_modules/@types/mocha/index.d.ts(42,13): error TS2403: Subsequent variable declarations must have the same type.  Variable 'it' must be of type 'It', but here has type 'ITestDefinition'.
node_modules/@types/mocha/index.d.ts(43,13): error TS2403: Subsequent variable declarations must have the same type.  Variable 'xit' must be of type 'It', but here has type 'ITestDefinition'.
node_modules/@types/mocha/index.d.ts(45,13): error TS2403: Subsequent variable declarations must have the same type.  Variable 'test' must be of type 'It', but here has type 'ITestDefinition'.
node_modules/@types/mocha/index.d.ts(63,18): error TS2300: Duplicate identifier 'beforeEach'.
node_modules/@types/mocha/index.d.ts(64,18): error TS2300: Duplicate identifier 'beforeEach'.
node_modules/@types/mocha/index.d.ts(65,18): error TS2300: Duplicate identifier 'afterEach'.
node_modules/@types/mocha/index.d.ts(66,18): error TS2300: Duplicate identifier 'afterEach'.
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! @shd101wyy/mume@0.2.8 build: `tsc -p .`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the @shd101wyy/mume@0.2.8 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/shd101wyy/.npm/_logs/2018-01-15T04_43_00_707Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! @shd101wyy/mume@0.2.8 prepare: `npm run build`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the @shd101wyy/mume@0.2.8 prepare script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/shd101wyy/.npm/_logs/2018-01-15T04_43_00_725Z-debug.log
```

Do you have any idea how to fix it? 
Again, thank you very much for your contribution ;)

**Comment by kachkaev** [comment]
Hmmm... I confirm this. Will have a look now!

**Comment by kachkaev** [comment]
Should be good now! @shd101wyy could you please try the latest commit?

What were you using `@types/mocha` for? We don't need this any more because `@types/jest` should have the same defs. But still worth checking if I haven't broken anything.

**Comment by shd101wyy** [comment]
@kachkaev Yes `@types/mocha` is not used. You can remove it if necessary.
I will try your update later when I have time.
Thank you very much.

**Comment by kachkaev** [comment]
It’s been removed in the previous commit ;-)

**Comment by kachkaev** [comment]
After noticing that attributes are not only used in code, but also in https://github.com/shd101wyy/markdown-preview-enhanced/issues/559 for example, moved `stringifyAttributes()` from `code-chunk-attributes.ts` to `lib/attributes.ts`. This new file also contains `stringifyAttributes()` now, which has been moved from `utility.ts`. Finally, I switched to importing these two functions directly from `lib/attributes` as a step towards more granular dependencies in future.

Both functions are covered with tests.

**Pull request merged**
